### ISSUE TITLE
Use intersection types to allow strong typing of jasmine Spys

### ISSUE THREAD

**Issue by zakhenry** [henrysun918/mock-factory#1]
Hey nice project!

I was working on something similar was looking for something open source and found this. I found that you can tighten up the typing by defining an intersection type return on the create method. eg

```ts
export class MockFactory {
    /**
     * create a mock object that has the identical interface with the class you passed in
     */
    public static create<T extends object>(blueprint: Type<T> | T): Proxy<T> & {[M in keyof T]: jasmine.Spy} {
```

It allows you to do 
```ts
mockClass1Instance = MockFactory.create(Class1);
mockClass1Instance.publicMethod.and.returnValue(999);
```

Without having to type cast `mockClass1Instance.publicMethod as jasmine.Spy`

Hope it helps!

**Comment by chuanqisun** [comment]
Thanks for the input!

One potential problem with the intersection is that `[M in keyof T]: jasmine.Spy` will also include the members that are not functions. In that case, there are no spies behind them.
```TypeScript
class RealClass {
    public someProperty: number;
}

mockingClass = MockFactory.create(RealClass)

// with intersection
mockingClass.someProperty.and.return(42); // runtime error, 'and' does not exist on undefined
```

I'll play with it this weekend and see if I can add spies to the non-function members of the class. I feel [spyOnProperty](https://jasmine.github.io/api/2.6/global.html#spyOnProperty) is a right direction to go but I still haven't come up with a solution. Please let me know if you have any new findings.

Thanks again!

**Comment by zakhenry** [comment]
Ah good point about properties, however I think you're on to something with the spyOnProperty

**Comment by chuanqisun** [comment]
#2 added typing to function, getter, and setter spies under a `_spy` facade
