### ISSUE TITLE
Key assignment error TypeScript 2.9

### ISSUE THREAD

**Issue by Wardrium** [henrysun918/mock-factory#9]
[TypeScript 2.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html) made changes to keys so that they can be of types string | number | symbol, instead of just string. In src/lib/index.ts lines 82, 85, and 92, `propertyName: keyof T` is being passed into `ensureProperty` which takes a string, causing an error to occur when compiling with TypeScript 2.9.

**Comment by unlight** [comment]
```
node_modules/jasmine-mock-factory/src/lib/index.ts:82:41 - error TS2345: Argument of type 'keyof T' is not assignable to parameter of type 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

82                     this.ensureProperty(propertyName);
                                           ~~~~~~~~~~~~


node_modules/jasmine-mock-factory/src/lib/index.ts:85:41 - error TS2345: Argument of type 'keyof T' is not assignable to parameter of type 'string'.

85                     this.ensureFunction(propertyName);
                                           ~~~~~~~~~~~~


node_modules/jasmine-mock-factory/src/lib/index.ts:92:37 - error TS2345: Argument of type 'keyof T' is not assignable to parameter of type 'string'.

92                 this.ensureProperty(propertyName);
                                       ~~~~~~~~~~~~

```

**Comment by unlight** [comment]
@chuanqisun

**Comment by chuanqisun** [comment]
Thank you @Wardrium for the report and @unlight for looking into it. I'm working on a fix.

**Comment by chuanqisun** [comment]
done! 2.1.0 release should get this patched. Let me know if you still see any errors after the update.

Thank you!

**Comment by chuanqisun** [comment]
I also noticed michael-silva [forked the library]( https://github.com/michael-silva/jasmine-mock-factory) and fixed the issue with a slightly different approach.  Kudos to the community!

That fork should prevent the ts compiler error but didn't address the root cause. If someone actually uses a symbol as the property name, the test will break. My fix added the error checking and warning message when symbols are used.
